name: Merolagani Scraper

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust time as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas pyarrow
    
    - name: Run scraper
      run: |
        python merolagani_scraper.py
    
    - name: Upload scraped data
      uses: actions/upload-artifact@v2
      with:
        name: floorsheet-data
        path: floorsheet_data/
        retention-days: 7
